# Site settings
title: Tiny Kite
email: dsexton@dakotasexton.com
description: Tiny Kite is a design studio run by Dakota Sexton. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tinyite.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
